Script started on Thu 06 Feb 2020 10:45:13 AM PST
]0;dotagiri@bondi:~/hw2[dotagiri@bondi ~/hw2]$ logout[25Gcd[Klsvi PhotoLab.c[25G./PhotoLab[K[25G[41@gcc -lm -ansi -std=c99 -Wall PhotoLab.c -o [76G
]0;dotagiri@bondi:~/hw2[dotagiri@bondi ~/hw2]$ gcc -lm -ansi -std=c99 -Wall PhotoLab.c -o PhotoLab[25Glogout[K[25Gcd[Klsvi PhotoLab.c[25G./PhotoLab[K
----------------------------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Test all functions
7: Exit
----------------------------------------------
Please make your choice:1
Please input the file name to load: applestore
applestore.ppm was read successfully!
----------------------------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Test all functions
7: Exit
----------------------------------------------
Please make your choice:6
applestore.ppm was read successfully!
aging.ppm was saved successfully. 
aging.jpg was stored for viewing. 
Aging tested!

applestore.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

applestore.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

applestore.ppm was read successfully!
hue.ppm was saved successfully. 
hue.jpg was stored for viewing. 
Hue tested!

AutoTest complete!
----------------------------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Test all functions
7: Exit
----------------------------------------------
Please make your choice:7
]0;dotagiri@bondi:~/hw2[dotagiri@bondi ~/hw2]$ exit
exit

Script done on Thu 06 Feb 2020 10:45:44 AM PST
