Script started on Tue 18 Feb 2020 09:50:58 AM PST
]0;dotagiri@bondi:~/hw3[dotagiri@bondi ~/hw3]$ make[K[Kke clean
rm -f *.o
rm -f PhotoLab
rm -f PhotoLabTest
]0;dotagiri@bondi:~/hw3[dotagiri@bondi ~/hw3]$ make
gcc -c -Wall -ansi -std=c99 PhotoLab.c -o PhotoLab.o
gcc -c -Wall -ansi -std=c99 FileIO.c -o FileIO.o
gcc -c -Wall -ansi -std=c99 DIPs.c -o DIPs.o
gcc -c -Wall -ansi -std=c99 Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -lm -Wall -ansi -std=c99 PhotoLab.o FileIO.o -L. -lfilter -o PhotoLab
gcc -c -DDEBUG -Wall -ansi -std=c99 PhotoLab.c -o PhotoLabTest.o
gcc -lm -Wall -ansi -std=c99 PhotoLabTest.o FileIO.o -L. -lfilter -o PhotoLabTest
]0;dotagiri@bondi:~/hw3[dotagiri@bondi ~/hw3]$ ./PhotoLab

-------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Add noise to an image
7: Posterize an image
8: Motion Blur
9: Test all functions
10: Exit
--------------------------
Please make your choice: 9
CrystalChurch.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
CrystalChurch.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
CrystalChurch.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
CrystalChurch.ppm was read.
noise.ppm was saved. 
noise.jpg was stored.
CrystalChurch.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
CrystalChurch.ppm was read.
blur.ppm was saved. 
blur.jpg was stored.

-------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Add noise to an image
7: Posterize an image
8: Motion Blur
9: Test all functions
10: Exit
--------------------------
Please make your choice: 10
You exit the program.
]0;dotagiri@bondi:~/hw3[dotagiri@bondi ~/hw3]$ ./[K[Kmake PhotoLabTest
make: `PhotoLabTest' is up to date.
]0;dotagiri@bondi:~/hw3[dotagiri@bondi ~/hw3]$ ./PhotoLabTest
CrystalChurch.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
Black and White tested!

CrystalChurch.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
Sharpen tested!

CrystalChurch.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
Hue tested!

CrystalChurch.ppm was read.
noise.ppm was saved. 
noise.jpg was stored.
Noise tested!

CrystalChurch.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
Posterize tested!

CrystalChurch.ppm was read.
blur.ppm was saved. 
blur.jpg was stored.
Motion Blur tested!

]0;dotagiri@bondi:~/hw3[dotagiri@bondi ~/hw3]$ touch Advanced.c
]0;dotagiri@bondi:~/hw3[dotagiri@bondi ~/hw3]$ make PhotoLab
gcc -c -Wall -ansi -std=c99 Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -lm -Wall -ansi -std=c99 PhotoLab.o FileIO.o -L. -lfilter -o PhotoLab
]0;dotagiri@bondi:~/hw3[dotagiri@bondi ~/hw3]$ exit
exit

Script done on Tue 18 Feb 2020 09:52:02 AM PST
